### ISSUE TITLE
Route wasn't reloaded in example

### ISSUE THREAD

**Issue by meotimdihia** [lependu/fastify-webpack-hmr#4]
The route wasn't reloaded in the example.
I tried with a command: "npm run example".
Can you suggest me about this?

**Comment by lependu** [comment]
Hi! I just give a try the latest version (v2.0.1) and it is working just fine for me.
In order to be able to give you any suggetion, i need some information:
- the output of the command
- your environment (OS, node version)
- the version of this plugin and fastify which you use 
- how did you test if it is working for you

**Comment by meotimdihia** [comment]
![ezgif-5-df897f6ba30e](https://user-images.githubusercontent.com/300961/54859589-83be2380-4d41-11e9-972c-de99108cef9e.gif)

I changed route "/" to "/hello". But it doesn't work

**Comment by lependu** [comment]
This plugin is for client side hot reloading. So it works with `example/client.js` and `example/message.js` . For server side hot reloading you can use [nodemon](https://www.npmjs.com/package/nodemon) for example.

**Comment by meotimdihia** [comment]
Thanks, I close this issue.
