### ISSUE TITLE
Support for React Router Routes

### ISSUE THREAD

**Issue by miguel-orange** [lependu/fastify-webpack-hmr#8]
How would I be able to support react router routes? When I visit `/route`, I'm getting a 404.
For production react router routes work as expected with https://github.com/fastify/fastify-static

**Comment by lependu** [comment]
Hi!

Thanks to checking out this repo!

I never tried to setup with react router, usually I use this with pure js. Can you give some code snippet (or even better an example repo) how you tried to set it up?

**Comment by miguel-orange** [comment]
Here's a basic example of react router. When you click a link the url will change. This works as expected with fastify-webpack-hmr. When you refresh or go to the link directly fastify returns a 404.
I believe I've used https://github.com/webpack-contrib/webpack-hot-middleware ,express, and react router in the past.

**Comment by lependu** [comment]
I am sorry, but I still can't figure out what you try to achieve here. First of all your example is an express app and don't see how fastify comes here. Secondly I don't see any route declaration, so it is not a surprise you get 404. 

Do you want to render a page on server side and kickoff the react router (which works on client side) when a page loaded? If that is the case, take a look at [next.js](https://github.com/zeit/next.js) which does exactly the same but with his own router. And you can check out the [fastify-nextjs](https://github.com/fastify/fastify-nextjs) plugin.

**Comment by ericmacfa** [comment]
I ran into this issue while porting one of my applications from Express to Fastify.

@lependu To add some additional context, the crux of the issue is that Single Page Applications (SPA) use browser-side routing to dynamically display content without fetching each individual page from the server.

For Express, I have used [connect-history-api-fallback](https://www.npmjs.com/package/connect-history-api-fallback).
Additionally, `webpack-dev-server` has [built-in support](https://github.com/webpack/webpack-dev-server/tree/master/examples/cli/history-api-fallback) for this pattern (which internally leverages `connect-history-api-fallback`).

Unfortunately, the `connect-history-api-fallback` middleware does not work with Fastify, as it relies on modifying `request.url` which does not exist in Fastify.

I propose adding a configuration option `historyApiFallback`, similar to what `webpack-dev-server` offers, which would trigger logic analogous to `connect-history-api-fallback` (but specific to Fastify).

**Comment by ericmacfa** [comment]
Just to clarify: the logic that I mentioned above could (and should) be implemented in a separate plugin, and then leveraged within this package.

**Comment by ericmacfa** [comment]
I googled around a bit more, and I stumbled upon [this thread](https://github.com/webpack/webpack-dev-middleware/issues/39#issuecomment-139912223) on `webpack-dev-middleware`, which led me to the following solution to this issue:
```
const path = require('path');
// ...
fastify.use(webpackDevMiddleware);
fastify.use(webpackHotMiddleware);
// ...
fastify.get(`/*`, function(request, response) {
    const indexPath = path.join(webpackConfig.output.path, 'index.html');
    const index = webpackDevMiddleware.fileSystem.readFileSync(indexPath);

    response.type('text/html').send(index);
});
```

Interestingly, documentation was added for this approach in [webpack-dev-middleware !44](https://github.com/webpack/webpack-dev-middleware/pull/44/files), but was subsequently removed (I have yet to track down why).

**Comment by lependu** [comment]
Hi! Thank you to track this down, I think, you summarized the problem precisely.

Adding `client side routing` support is a very complex feature, and that is the reason why I am not intend to bring that into this plugin.

On top of that, client side routing support is implemented in packages like next.js and nuxt.js, and they provide support to use them with custom servers like Fastify. That is the other reason why I rather use those packages, than implement the feature here. 

If you determined to implement the client side routing support, I think your evaulation is spot on. The first step would be to create a `fastify-connect-history-api-fallback` plugin which uses the hook and decorator system provided by Fastify, instead of modifying the core request object. As soon as that module exists, we can implement a configuration option here, which feature I am happy to add this plugin.

**Comment by storkweb** [comment]
Hi,
I had the same problem with Vue SPA with history mode. Just found the solution by using "@vottuscode/fastify-vue-static" instead of "fastify-static" works like a charm :-)
